require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Rakuten-Reward-SDK/Reward-SDK-iOS.git'
platform :ios, '11.0'

target 'RakutenRewarkExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

   pod 'react-native-rakuten-rewark', :path => '../..'
   pod 'RakutenRewardSDK'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  use_flipper!()
  post_install do |installer|
    flipper_post_install(installer)
  end
end
